
export const TEAMLISTS = [
  {
    group: 'Premier League',
    teams: [
      { en: 'Everton', ko: '에버턴', img: 'https://sports-phinf.pstatic.net/team/wfootball/default/8.png' },
      { en: 'Aston Villa', ko: '아스톤 빌라', img: 'https://sports-phinf.pstatic.net/team/wfootball/default/2.png' },
      { en: 'Leicester', ko: '레스터', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/29.png&type=f25_25&refresh=1' },
      { en: 'Arsenal', ko: '아스널', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/1006.png&type=f25_25&refresh=1' },
      { en: 'Liverpool', ko: '리버풀', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/9.png&type=f25_25&refresh=1' },
      { en: 'Tottenham', ko: '토트넘', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/19.png&type=f25_25&refresh=1' },
      { en: 'Chelsea', ko: '첼시', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/4.png&type=f25_25&refresh=1' },
      { en: 'Leeds', ko: '리즈', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/28.png&type=f25_25&refresh=1' },
      { en: 'Newcastle', ko: '뉴캐슬', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/31.png&type=f25_25&refresh=1' },
      { en: 'West Ham', ko: '웨스트햄', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/43.png&type=f25_25&refresh=1' },
      { en: 'Southampton', ko: '사우샘프턴', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/18.png&type=f25_25&refresh=1' },
      { en: 'Crystal Palace', ko: '크리스탈 팰리스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/5.png&type=f25_25&refresh=1' },
      { en: 'Wolves', ko: '울버햄튼 원더러스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/44.png&type=f25_25&refresh=1' },
      { en: 'Manchester City', ko: '맨체스터 시티', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/11.png&type=f25_25&refresh=1' },
      { en: 'Brighton', ko: '브라이튼', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/6795.png&type=f25_25&refresh=1' },
      { en: 'Manchester United', ko: '맨체스터 유나이티드', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/12.png&type=f25_25&refresh=1' },
      { en: 'West Brom', ko: '웨스트 브로미치', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/42.png&type=f25_25&refresh=1' },
      { en: 'Burnley', ko: '번리', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/70.png&type=f25_25&refresh=1' },
      { en: 'Sheffield Utd', ko: '셰필드 유나이티드', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/37.png&type=f25_25&refresh=1' },
      { en: 'Fulham', ko: '풀럼', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/55.png&type=f25_25&refresh=1' },
    ]
  },
  {
    group: 'LaLiga',
    teams: [
      { en: 'Real Madrid', ko: '레알 마드리드', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26303.png&type=f25_25&refresh=1' },
      { en: 'Real Betis', ko: '레알 베티스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26314.png&type=f25_25&refresh=1' },
      { en: 'Real Sociedad', ko: '레알 소시에다드', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26308.png&type=f25_25&refresh=1' },
      { en: 'Villarreal', ko: '비야레알', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/38295.png&type=f25_25&refresh=1' },
      { en: 'Barcelona', ko: '바르셀로나', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26300.png&type=f25_25&refresh=1' },
      { en: 'Sevilla', ko: '세비야', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27821.png&type=f25_25&refresh=1' },
      { en: 'Getafe', ko: '헤타페', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/37459.png&type=f25_25&refresh=1' },
      { en: 'Valencia', ko: '발렌시아', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26316.png&type=f25_25&refresh=1' },
      { en: 'Cadiz', ko: '카디스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/4488.png&type=f25_25&refresh=1' },
      { en: 'Granada CF', ko: '그라나다 CF', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/41000.png&type=f25_25&refresh=1' },
      { en: 'Osasuna', ko: '오사수나', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27152.png&type=f25_25&refresh=1' },
      { en: 'Atletico Madrid', ko: '아틀레티코 데 마드리드', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26305.png&type=f25_25&refresh=1' },
      { en: 'Celta Vigo', ko: '셀타 데 비고', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26302.png&type=f25_25&refresh=1' },
      { en: 'Eibar', ko: '에이바르', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/37452.png&type=f25_25&refresh=1' },
      { en: 'Huesca', ko: '우에스카', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/24265.png&type=f25_25&refresh=1' },
      { en: 'Elche', ko: '엘체', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/2846.png&type=f25_25&refresh=1' },
      { en: 'Alaves', ko: '알라베스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26476.png&type=f25_25&refresh=1' },
      { en: 'Levante', ko: '레반테', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/37454.png&type=f25_25&refresh=1' },
      { en: 'Athletic Club', ko: '아틀레틱 클루브', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26313.png&type=f25_25&refresh=1' },
      { en: 'Valladolid', ko: '바야돌리드', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26319.png&type=f25_25&refresh=1' },
    ]
  },
  {
    group: 'Bundesliga',
    teams: [
      { en: 'RB Leipzig', ko: 'RB 라이프치히', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/61019.png&type=f25_25&refresh=1' },
      { en: 'FC Augsburg', ko: 'FC 아우크스부르크', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/32656.png&type=f25_25&refresh=1' },
      { en: 'Eintracht Frankfurt', ko: '아인트라흐트 프랑크푸르트', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26460.png&type=f25_25&refresh=1' },
      { en: 'Bayern Munich', ko: '바이에른 뮌헨', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26247.png&type=f25_25&refresh=1' },
      { en: 'Borussia Dortmund', ko: '도르트문트', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26261.png&type=f25_25&refresh=1' },
      { en: '1899 Hoffenheim', ko: '1899 호펜하임', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/48490.png&type=f25_25&refresh=1' },
      { en: 'Werder Bremen', ko: '베르더 브레멘', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26252.png&type=f25_25&refresh=1' },
      { en: 'VfB Stuttgart', ko: 'VfB 슈투트가르트', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26250.png&type=f25_25&refresh=1' },
      { en: 'Union Berlin', ko: '우니온 베를린', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/2547.png&type=f25_25&refresh=1' },
      { en: 'Arminia Bielefeld', ko: '아르미니아 빌레펠트', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/2540.png&type=f25_25&refresh=1' },
      { en: 'Borussia Monchengladbach', ko: '보루시아 묀헨글라트바흐', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26259.png&type=f25_25&refresh=1' },
      { en: 'SC Freiburg', ko: 'SC 프라이부르크', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26461.png&type=f25_25&refresh=1' },
      { en: 'Hertha Berlin', ko: '헤르타 BSC', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26263.png&type=f25_25&refresh=1' },
      { en: 'Bayer Leverkusen', ko: '바이어 레버쿠젠', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26256.png&type=f25_25&refresh=1' },
      { en: 'VfL Wolfsburg', ko: 'VfL 볼프스부르크', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26257.png&type=f25_25&refresh=1' },
      { en: 'FC Koln', ko: 'FC 쾰른', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26260.png&type=f25_25&refresh=1' },
      { en: 'FSV Mainz 05', ko: 'FSV 마인츠 05', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/32676.png&type=f25_25&refresh=1' },
      { en: 'FC Schalke 04', ko: 'FC 샬케 04', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26249.png&type=f25_25&refresh=1' },
    ]
  },
  {
    group: 'Serie A',
    teams: [
      { en: 'Atalanta', ko: '아탈란타', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26364.png&type=f25_25&refresh=1' },
      { en: 'AC Milan', ko: 'AC 밀란', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26368.png&type=f25_25&refresh=1' },
      { en: 'Sassuolo', ko: '사수올로', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/53908.png&type=f25_25&refresh=1' },
      { en: 'Inter', ko: '인터', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/6136.png&type=f25_25&refresh=1' },
      { en: 'Napoli', ko: '나폴리', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26370.png&type=f25_25&refresh=1' },
      { en: 'Verona', ko: '베로나', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27648.png&type=f25_25&refresh=1' },
      { en: 'Benevento', ko: '베네벤토', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/2759.png&type=f25_25&refresh=1' },
      { en: 'Juventus', ko: '유벤투스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26359.png&type=f25_25&refresh=1' },
      { en: 'Lazio', ko: '라치오', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26362.png&type=f25_25&refresh=1' },
      { en: 'AS Roma', ko: 'AS 로마', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26357.png&type=f25_25&refresh=1' },
      { en: 'Genoa', ko: '제노아', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/6894.png&type=f25_25&refresh=1' },
      { en: 'Bologna', ko: '볼로냐', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26371.png&type=f25_25&refresh=1' },
      { en: 'Fiorentina', ko: '피오렌티나', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26366.png&type=f25_25&refresh=1' },
      { en: 'Sampdoria', ko: '삼프도리아', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26361.png&type=f25_25&refresh=1' },
      { en: 'Spezia', ko: '스페지아', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/2735.png&type=f25_25&refresh=1' },
      { en: 'Parma Calcio 1913', ko: '파르마 칼초 1913', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26358.png&type=f25_25&refresh=1' },
      { en: 'Cagliari', ko: '칼리아리', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26474.png&type=f25_25&refresh=1' },
      { en: 'Torino', ko: '토리노', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27038.png&type=f25_25&refresh=1' },
      { en: 'Udinese', ko: '우디네세', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26360.png&type=f25_25&refresh=1' },
      { en: 'Crotone', ko: '크로토네', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/38624.png&type=f25_25&refresh=1' },
    ]
  },
  {
    group: 'Ligue 1',
    teams: [
      { en: 'Rennes', ko: '렌', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26349.png&type=f25_25&refresh=1' },
      { en: 'Lille', ko: '릴', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27372.png&type=f25_25&refresh=1' },
      { en: 'Lens', ko: '랑스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26342.png&type=f25_25&refresh=1' },
      { en: 'Paris Saint Germain', ko: '파리 생제르맹', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26339.png&type=f25_25&refresh=1' },
      { en: 'Montpellier', ko: '몽펠리에', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26351.png&type=f25_25&refresh=1' },
      { en: 'Monaco', ko: '모나코', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26343.png&type=f25_25&refresh=1' },
      { en: 'Saint Etienne', ko: '생테티엔', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27408.png&type=f25_25&refresh=1' },
      { en: 'Nice', ko: '니스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/27462.png&type=f25_25&refresh=1' },
      { en: 'Bordeaux', ko: '보르도', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26340.png&type=f25_25&refresh=1' },
      { en: 'Marseille', ko: '마르세유', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26344.png&type=f25_25&refresh=1' },
      { en: 'Stade Brestois 29', ko: '스타드 브레스투아 29', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/1715.png&type=f25_25&refresh=1' },
      { en: 'Angers', ko: '앙제', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/32839.png&type=f25_25&refresh=1' },
      { en: 'Nimes', ko: '님', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/1663.png&type=f25_25&refresh=1' },
      { en: 'Lyon', ko: '리옹', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26345.png&type=f25_25&refresh=1' },
      { en: 'Metz', ko: '메스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/6832.png&type=f25_25&refresh=1' },
      { en: 'Nantes', ko: '낭트', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26350.png&type=f25_25&refresh=1' },
      { en: 'Lorient', ko: '로리앙', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26469.png&type=f25_25&refresh=1' },
      { en: 'Strasbourg', ko: '스트라스부르', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/26354.png&type=f25_25&refresh=1' },
      { en: 'Reims', ko: '랭스', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/41053.png&type=f25_25&refresh=1' },
      { en: 'Dijon', ko: '디종', img: 'https://dthumb-phinf.pstatic.net/?src=https://sports-phinf.pstatic.net/team/wfootball/default/28023.png&type=f25_25&refresh=1' },
    ]
  },
];
